#!/usr/bin/env python3
"""Generate review-ready StartupSimulator QA drafts from frozen evidence."""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent
DATA = ROOT.parent.parent / "data"


def q(question, answer, category, *evidence):
    return {
        "question": question,
        "answer": answer,
        "category": category,
        "sources": list(evidence),
    }


DRAFTS = {
    "startupsimulator_01_main-build": [
        q("What was the original goal of StartupSimulator?", "To create a local startup-simulator web game with an office that a founder character navigates by clicking.", 4, (1, "Let's make a startup simulator indie game. We can start by just making an office space in which we navigate a founder character that moves around by clicking. Make it a local web app to run the game.")),
        q("What was the initial StartupSimulator prototype called?", "It was called Zero to One.", 4, (9, "Built **Zero to One**, a playable startup-office prototype.")),
        q("How did the original click-to-walk system handle furniture?", "It routed the founder around furniture.", 4, (9, "**Click-to-walk** founder movement that routes around furniture.")),
        q("Which non-mouse controls and convenience features shipped in the first prototype?", "It included keyboard movement, touch support, zoom, pause, and automatic browser saving.", 4, (9, "Keyboard movement, touch support, zoom, and pause."), (9, "Progress saved automatically in your browser.")),
        q("Were hiring and revenue systems part of the first prototype?", "No. The first version focused on office exploration; hiring, revenue, and broader business simulation were not implemented.", 5, (9, "This first version focuses on exploring the office; hiring, revenue, and broader business simulation aren’t implemented yet.")),
        q("How did the world projection change during the first Pokémon-style conversion?", "It changed from an isometric projection to a top-down orthographic projection.", 4, (45, "Changed from isometric projection to **top-down orthographic**")),
        q("What tile and room dimensions were introduced for the grid-based world?", "The conversion used 32-pixel tiles and expanded the room to 16 by 12 tiles.", 4, (45, "Introduced `TILE_SIZE = 32` for Pokemon-style 32px tiles"), (45, "Expanded room size from 12x10 to **16x12 tiles**")),
        q("How was the page layout changed to make the game full-screen?", "The old page layout was removed, the canvas became a 100vw by 100vh first child of the body, and fixed HUD overlays were placed at the top and bottom.", 4, (88, "**Removed** the entire old layout: topbar, sidebar, app-layout, scene wrapper, footer"), (88, "**Canvas is now fullscreen** (`#game` is the first child of `<body>`, styled `100vw × 100vh`)"), (88, "**Pokemon-style HUD overlay (bottom):** Character card with green HP bar + 4 task shortcut buttons")),
        q("Which rendering techniques were used in the temporary smooth animated redesign?", "It enabled high-quality image smoothing, fractional scaling, rounded rectangles, gradients, ellipses, curved paths, and object shadows.", 4, (125, "`imageSmoothingEnabled = true` + `imageSmoothingQuality = 'high'"), (125, "Fractional scale (`Math.max(0.5, raw)`"), (125, "`ctx.roundRect()` everywhere"), (125, "Linear and radial gradients on every surface for depth")),
        q("What replaced the green checkerboard floor in the smooth redesign?", "A warm wood-plank parquet floor with grain lines and plank-joint seams.", 4, (125, "**Floor:** Warm wood-plank parquet with horizontal grain lines + vertical plank-joint seams, instead of green checkerboard")),
        q("How many frames did the smooth character's walk cycle use?", "It used a four-frame walk cycle with opposing arm and leg motion and body bobbing.", 4, (125, "**4-frame walk cycle**: legs swing forward/back using `sin(time)`, arms swing in opposition, body bobs")),
        q("How did the rendering style change after the smooth animated redesign?", "The game reversed course from anti-aliased smooth rendering to crisp pixel art with image smoothing disabled and integer scaling.", 2, (125, "`imageSmoothingEnabled = true` + `imageSmoothingQuality = 'high'"), (141, "`imageSmoothingEnabled = false` — crisp pixel art"), (141, "Scale is `Math.floor(raw)`")),
        q("How does the later pixel-art character show its facing direction?", "Its eye positions change when facing left, right, or down, while facing up shows the back of the head without a face.", 4, (141, "**Direction-aware**: different eye positions for left/right/down; facing up shows back of head (no face, just ears)")),
        q("What happens when the player clicks a point occupied by furniture or a wall?", "The game searches outward in quarter-tile steps and routes Alex to the nearest walkable point within three tiles.", 4, (154, "Otherwise spirals outward in 0.25-tile steps"), (154, "returns the closest walkable point it finds (within 3 tiles)")),
        q("Which four tasks defined the original single-day objective?", "Walk around, brew coffee, pin an idea, and build a prototype.", 4, (158, "The objective is to complete **4 tasks**"), (158, "**Walk around**"), (158, "**Brew a coffee**"), (158, "**Pin your first idea**"), (158, "**Build a prototype**")),
        q("What was the original day's only meaningful constraint?", "Energy was the only real constraint, and the clock had no fail state when time ran out.", 4, (158, "**The only real constraint** is energy"), (158, "there's no fail state for running out of time")),
        q("How did the game's objective expand beyond its initial day-one experience?", "It changed from a short single-day experience into a ten-day sprint in which the four daily tasks advance the startup toward launch.", 2, (158, "it's a short, chill \"day one\" experience, not a deep sim"), (180, "### The core loop: 10-day sprint to launch"), (180, "Every day you complete the same 4 tasks")),
        q("What resets when a normal day is completed in the ten-day loop?", "The tasks, clock, distance counter, and Alex's position reset, while energy recovers by 30 up to a maximum of 100.", 4, (180, "**Resets** tasks, clock (back to 9 AM), distance counter, Alex's position"), (180, "**Partial energy recovery** (+30, capped at 100)")),
        q("What progression arc does the ten-day work task follow?", "It progresses from prototype through improvement, feedback, polish, demo, paid features, product feel, launch preparation, and a final push to launch.", 4, (180, "The arc goes: *prototype → improve → user feedback → polish → demo → paid features → product feel → launch prep → final push → **LAUNCH** 🚀*")),
        q("What happens after completing all tasks on Day 10?", "The game shows the full win message and offers Play again, which resets the game to Day 1.", 4, (180, "Day 10 complete → toast fires immediately, then day-end screen with the full win message and \"Play again\" which full-resets to Day 1.")),
        q("How were invisible collision margins reduced in the final movement fix?", "The founder radius was reduced from 0.4 to 0.18 tiles, and furniture padding was separated into a fixed 0.05-tile constant.", 4, (188, "**`FOUNDER_RADIUS` cut from 0.4 → 0.18`**"), (188, "Object collision padding — **separated and tightened to 0.05**")),
        q("Was the visible checkerboard floor gone by the end of the main trajectory?", "No. The final researcher message explicitly said the checkerboard pattern was still visible.", 5, (141, "Top-down RPG tilemap: alternating warm-tan checker tiles"), (193, "I can clearly still see a checkerboard pattern on the floor.")),
    ],
    "startupsimulator_02_hiring-workers": [
        q("What simple hiring interaction was proposed during the initial brainstorm?", "The player would click the ideas desk, review a candidate profile, and choose whether to hire or pass; a hire would add a character and a delegatable daily task.", 4, (2, "The player clicks it, gets a dialog with a candidate profile (name, role, trait), and decides **Hire / Pass**."), (2, "Hiring adds a visible new character sprite to the office and unlocks a daily **delegate** task")),
        q("How much money does founder work earn across the ten-day progression?", "Work earnings scale from $50 on Day 1 to $5,000 on Day 10.", 4, (29, "scaling from **$50 on Day 1** up to **$5,000 on Day 10**")),
        q("Does the founder's money survive a browser reload?", "Yes. Money is restored by parseSave and persists across sessions.", 5, (29, "Added `money` restoration to `parseSave()` — persists across sessions")),
        q("Where can the player hire workers?", "At either the Room for a cofounder ideas desk or the second desk in the top-left area.", 4, (52, "Walk to the **\"Room for a cofounder\" desk** (ideas) or the new **second desk** (top-left area) and click to interact.")),
        q("Do the available candidates change during the same in-game day?", "No. Candidates are deterministic within a day, but different days offer different candidates.", 5, (52, "Candidates are deterministic per day (same candidates all day, different each day).")),
        q("What are the passive base earnings rates for the four worker roles?", "Engineers earn $3 per second, Growth workers $4, Designers $2, and Operations workers $2.", 4, (52, "Rates: Engineer $3/s · Growth $4/s · Designer $2/s · Operations $2/s.")),
        q("How many workers can the player hire at once?", "Up to two, one for each worker desk.", 4, (52, "Up to **2 workers** can be hired (one per desk).")),
        q("How are worker roles distinguished visually?", "Their seated sprites are color-coded: blue for Engineer, pink for Designer, green for Growth, and orange for Operations.", 4, (52, "colour-coded to their role (blue = Engineer, pink = Designer, green = Growth, orange = Operations)")),
        q("How do worker upgrades affect earnings and what do they cost?", "Level 2 costs $500 and earns 1.5 times the base rate; level 3 costs $2,000 and earns 2.25 times the base rate.", 4, (92, "level 1 = base rate, level 2 = 1.5×, level 3 = 2.25×; upgrade cost $500/$2000")),
        q("What are the three founder efficiency upgrades?", "Focus Mode costs $300 and lowers work energy to 8; Speed Desk costs $800 and gives 1.5x work earnings; Deep Work Protocol costs $2,000 and gives 2x earnings while restoring 5 energy.", 4, (92, "🎯 **Focus Mode** ($300) — Work costs 8 energy instead of 12"), (92, "⚡ **Speed Desk** ($800) — Work earns 1.5× money per session"), (92, "🧠 **Deep Work Protocol** ($2000) — Work earns 2× money AND restores +5 energy instead of costing any")),
        q("How does the player fire a worker?", "The player opens an occupied desk and selects Let [Name] go; this removes the worker, saves, updates the HUD, and makes the desk available for hiring again.", 4, (100, "**\"Let [Name] go\" → fires them**"), (100, "The desk immediately resets to \"Room for someone great.\" / \"Another desk.\"")),
        q("What happens if the player leaves the worker-name field blank?", "The hire uses the candidate's default name; typing a custom name and pressing Enter or the offer button uses that name instead.", 4, (114, "reads `nameInput.value.trim()`, falls back to the candidate's default name if blank"), (114, "click \"Make the offer\" or hit **Enter**")),
        q("When can a newly hired worker go on strike?", "Each hire receives a random strike countdown of 60 to 180 real seconds.", 4, (126, "each worker gets a `strikeCountdown` of 60–180 real-seconds on hire")),
        q("Does a striking worker keep generating passive income?", "No. A worker earns $0 per second while on strike.", 5, (126, "the worker earns $0/s")),
        q("What two choices resolve a worker strike?", "The player can pay a one-time payoff or permanently raise the worker's wage by $1 per second.", 4, (126, "**\"Pay them off – $X\"** — one-time flat payment"), (126, "**\"Raise wages (+$1/s)\"** — permanently bumps `earningsPerTick` by 1")),
        q("How is a strike payoff priced?", "It costs 40 times the worker's current earnings rate after the level multiplier, roughly forty seconds of passive income.", 4, (126, "**Payoff cost**: `earningsPerTick × level_multiplier × 40` — roughly 40 seconds of passive income")),
        q("Where is the cereal station and how does the player reach it?", "It is a two-by-one object at x=7,y=7 with its own walk target; clicking either it or its HUD task routes the player there.", 4, (149, "A new 2×1 `cereal` object sits at `x:7, y:7`"), (149, "clicking it or the HUD button routes you there correctly")),
        q("What is the cereal station's two-stage interaction?", "The player first pays $25 to stock three servings, then pours a bowl that consumes one serving, restores 20 energy, and completes the cereal task.", 4, (149, "Costs $25, sets `cerealStock = 3`"), (149, "`cerealStock--`, `+20 energy`, completes the `cereal` task")),
        q("What happens to cereal stock when a new day begins?", "It resets to zero, so the station must be restocked each day.", 4, (149, "`cerealStock` resets to `0` each new day")),
        q("How does restocking cereal affect workers who are not on strike?", "It adds 60 seconds to every non-striking worker's remaining strike countdown.", 4, (153, "Every non-striking worker's `strikeCountdown` gets **+60 seconds** added")),
        q("Can cereal end an active worker strike?", "No. Workers who are already striking are unaffected by restocking.", 5, (153, "Workers who are *already on strike* are unaffected")),
        q("What happens when the player's money reaches one million dollars?", "A guarded trigger fires once at any time or day and opens a full-screen million-dollar win overlay with a Start over button.", 4, (161, "`changeMoney()` now checks `state.money >= 1_000_000` on every call"), (161, "A `wonMillionDollar` boolean guard ensures it fires exactly once."), (161, "A **\"Start over 🚀\"** button that resets the full game")),
    ],
    "startupsimulator_03_health-stamina": [
        q("Where was the bed placed in the office?", "It was placed at x=3, y=9 with a size of 3 by 2 tiles and an interaction target at x=6, y=10.", 4, (27, "position `x:3, y:9, w:3, d:2`"), (27, "The interaction target is `x:6, y:10`")),
        q("When is the player allowed to sleep?", "Only after the other four daily tasks are complete; sleeping then completes the fifth task and advances the day after 1.8 seconds.", 4, (27, "it's now the 5th and final daily task"), (27, "**All tasks done?**"), (27, "triggers `advanceDay()` after 1.8 seconds")),
        q("How did the first passive energy-drain loop work?", "It removed one energy every eight real seconds until the player slept.", 4, (42, "Every **8 real-seconds**, if the player hasn't slept yet today, 1 energy is drained.")),
        q("How does the game warn the player at low energy?", "At 20 energy or below it shows a one-time warning, turns the bar red, and makes it pulse.", 4, (42, "### Warning at ≤20 HP"), (42, "A **one-time warning toast** fires"), (42, "energy bar turns red and pulses")),
        q("What penalty follows ordinary burnout?", "The game advances to the next day with only 50 energy and shows a burnout-specific day-end screen.", 4, (42, "Advances to the next day **but only restores energy to 50**"), (42, "day-end overlay with a burnout variant")),
        q("Why could energy stop draining after reloading a saved game?", "A previously completed sleep task could be restored from localStorage, making the drain condition think the player had already slept; the fix excluded sleep from restored completions.", 4, (51, "`parseSave` restored it — so `state.completed.includes('sleep')` was `true`"), (51, "`'sleep'` is now explicitly excluded from the loaded `completed` list")),
        q("How was the passive drain rate made more aggressive?", "It changed from one point every eight seconds to one point every three seconds.", 2, (42, "Every **8 real-seconds**"), (55, "**1 HP every 3 seconds** instead of every 8")),
        q("What stamina tradeoff does coffee create?", "Coffee fills stamina to 100 but doubles the drain rate from one point every three seconds to one every 1.5 seconds.", 4, (63, "**After coffee:** fills to **100 HP**, but drain doubles to **1 HP every 1.5 seconds**")),
        q("How does coffee affect movement speed?", "It raises speed from 2.65 to 4.5, approximately 70 percent faster, until the day changes or the game resets.", 4, (69, "**Speed** → jumps from `2.65` to `4.5` (~70% faster movement)"), (69, "Both effects **reset at the start of each new day**")),
        q("What did pills do when first introduced?", "They restored up to 40 HP but slowed movement from 2.65 to 1.3.", 4, (81, "**Restores up to +40 HP**"), (81, "**Slows speed to `1.3`** (~half of normal `2.65`)")),
        q("What happened when the sofa was first removed?", "Both the sofa and coffee table disappeared, leaving open floor space in the lower-right corner.", 4, (88, "the sofa and coffee table are gone. The lower-right corner of the room is now open floor space")),
        q("What was the sofa's final role after the removal was reconsidered?", "It and the coffee table returned as non-interactive decorations that still rendered and blocked movement.", 2, (88, "the sofa and coffee table are gone"), (95, "back in the room as pure decoration"), (95, "they block movement, render as before, but clicking or hovering them does nothing")),
        q("How was the health bar reframed as stamina?", "The HUD label changed from green HP to amber ST; below 25 it still turns red and pulses, and player-facing copy now says stamina.", 4, (106, "**`ST`** label in amber/gold instead of the old green `HP`"), (106, "When it drops below 25 it flips to **red** and pulses"), (106, "say \"stamina\" throughout")),
        q("How did the pills mechanic change after stamina was introduced?", "It changed from restoring 40 HP while slowing the player to costing 25 stamina while boosting speed to 4.5.", 2, (81, "**Restores up to +40 HP**"), (81, "**Slows speed to `1.3`**"), (111, "Pills 💊 | **−25** (floors at 1) | fast (4.5)")),
        q("Can taking pills reduce stamina to zero?", "No. The cost floors stamina at one, preventing the pills from killing the player directly.", 5, (111, "**−25** (floors at 1)"), (111, "the guard prevents you from killing yourself to 0")),
        q("What design problem did the agent identify with coffee and pills?", "Both produced the same 4.5 speed, making coffee strictly better except when pills were physically closer.", 4, (113, "**Coffee and pills do the same thing now.** Both give you speed 4.5."), (113, "coffee is strictly better unless you physically can't reach it")),
        q("Why was coffee's accelerated stamina drain easy for players to miss?", "The drain rate was not shown in the interface, so the difference between 1.5-second and three-second drain intervals was invisible.", 4, (113, "**The stamina drain rate is invisible.**"), (113, "1.5s drain vs. 3s")),
        q("What distinct pills effect was suggested but not implemented in this trajectory?", "The agent suggested making pills slow stamina drain so they would be a defensive, sustainable alternative to risky coffee.", 4, (113, "Instead of speed, maybe pills *slow the drain rate*"), (113, "Coffee = burst/risky, pills = defensive/sustainable.")),
        q("How does peptide-shot mortality escalate within a day?", "The death chance rises by 20 percentage points per shot: 20, 40, 60, 80, then 100 percent on the fifth shot.", 4, (129, "| 1st | 20%"), (129, "| 2nd | 40%"), (129, "| 3rd | 60%"), (129, "| 4th | 80%"), (129, "| 5th | 100%")),
        q("What happens when a peptide shot kills the player?", "A dedicated overdose day-end screen appears and the player wakes with 30 stamina, which is harsher than ordinary burnout's 50.", 4, (129, "dedicated `💉 You overdid it.` day-end screen"), (129, "wakes up at **30 stamina** (harsher than burnout's 50)")),
        q("What happens when a peptide shot succeeds?", "It immediately restores stamina to full and shows a toast about how close the gamble was.", 4, (129, "**When it works:** full stamina instantly")),
        q("When does the peptide-shot counter reset?", "It resets on a normal day advance, burnout, peptide death, and a hard reset.", 4, (129, "`peptideShots` resets to 0 on `advanceDay`, `burnOut`, `peptideDeath`, and hard reset")),
    ],
    "startupsimulator_04_parkour": [
        q("Which objects were initially considered vaultable?", "Chairs, plants, pills, and peptide objects.", 4, (36, "`chair`, `plant`, `pills`, `peptide`")),
        q("How did the original sprint mechanic work?", "Holding Shift while moving roughly doubled speed, consumed one stamina every 0.7 seconds, and produced a five-ghost blue afterimage trail.", 4, (36, "Hold `Shift` while moving with WASD/arrows to run at ~2× speed"), (36, "Costs 1 stamina every 0.7 seconds"), (36, "5 ghost sprites that fade out")),
        q("How did the first vault implementation detect and execute a jump?", "While moving, Space scanned 1.5 tiles ahead for a vaultable object, crossed it in a 0.38-second arc, and required a walkable landing spot.", 4, (36, "scans 1.5 tiles ahead"), (36, "flies cleanly over the object to the other side (0.38s arc)"), (36, "Landing spot must be walkable")),
        q("When is the parkour daily task completed?", "It completes on the player's first successful vault over an object.", 4, (36, "Completes on first successful vault over an object")),
        q("How is the character's jump height calculated visually?", "The sprite rises according to the parabolic formula 4 times peak times t times one minus t, while its shadow remains on the floor and shrinks.", 4, (36, "parabolic `4·peak·t·(1-t)` curve"), (36, "The shadow stays on the floor and shrinks/fades as Alex rises")),
        q("Where were the three parkour shortcut tables placed?", "At x=8,y=2 near the work desk, x=3,y=4 between the coffee and ideas areas, and x=8,y=6 between the work and lounge areas.", 4, (54, "`vault-a` | `x:8, y:2`"), (54, "`vault-b` | `x:3, y:4`"), (54, "`vault-c` | `x:8, y:6`")),
        q("How do shortcut tables visually communicate that they are jumpable?", "They use warm amber bodies, pulsing edge strips, a hover emoji, and orientation-specific highlighted edges.", 4, (54, "**Warm amber/gold body**"), (54, "**Pulsing glowing edge strips**"), (54, "**🤸 emoji** pops above the table on hover")),
        q("How was table-vault detection improved?", "Vault reach increased from 1.5 to two tiles, and landing calculations began using the dominant movement axis and table dimensions.", 4, (54, "**Reach increased** from 1.5 → 2.0 tiles"), (54, "**Direction-aware landing**: uses the dominant movement axis")),
        q("How much stamina does a shortcut-table vault cost?", "One stamina, compared with two for regular vaultable objects at that stage.", 4, (54, "**Shortcut tables cost only −1 stamina** vs −2 for regular objects")),
        q("What did the first on-screen dash button do?", "It toggled approximately double-speed sprinting while movement keys were held, independently of the Shift key.", 4, (75, "**Click to toggle on** → Alex sprints at 2× speed"), (75, "**Keyboard `Shift`** still works exactly as before")),
        q("When did the toggle dash cancel itself automatically?", "It cancelled on depleted energy, pause, focus loss, day end, burnout, or reset.", 4, (75, "**Energy bottoms out**"), (75, "**Game paused**"), (75, "**Window loses focus**"), (75, "**Day end / burnout / reset**")),
        q("How did dash stamina consumption change?", "Its interval changed from one point every 0.7 seconds to one every 0.25 seconds, approximately 12 times the passive rate.", 2, (36, "Costs 1 stamina every 0.7 seconds"), (78, "**After:** 1 HP drained every **0.25 seconds**"), (78, "**~12× the passive rate**")),
        q("What penalty prevents repeated free-hop spam?", "A free hop costs four stamina and, after landing, slows movement to 40 percent and blocks another jump for 0.6 seconds.", 4, (86, "**After:** −4 stamina, 0.28s arc"), (86, "movement speed drops to **40%** of normal for 0.6 seconds"), (86, "can't jump again until the stumble clears")),
        q("How was the intermediate physical dash button styled?", "It became a raised 64-by-64-pixel dark-green arcade-style button with hover, pressed, active-glow, and disabled states.", 4, (92, "**Idle** | 64×64px dark green button"), (92, "raised/3D \"arcade button\" feel")),
        q("How did the dash control evolve from the toggle version to its final behavior?", "It changed from a toggle for continuous sprinting into a single-trigger blink that teleports Alex forward.", 2, (75, "**Click to toggle on**"), (109, "## Blink Dash"), (109, "Alex instantly teleports up to **3 tiles forward**")),
        q("How can the player activate Blink Dash?", "By pressing Q or clicking the on-screen Blink button.", 4, (109, "Press **Q** (or click the ⚡ **BLINK** button)")),
        q("How does Blink Dash avoid moving through walls or furniture?", "It samples the route in 24 increments and stops at the last walkable tile.", 4, (109, "steps forward in 24 increments and stops at the last walkable tile")),
        q("What are Blink Dash's stamina cost and cooldown?", "It costs eight stamina and has a 1.2-second cooldown.", 4, (109, "**Costs 8 stamina**"), (109, "**1.2 second cooldown**")),
        q("Which controls appear in the persistent legend?", "WASD for movement, Shift for sprint, Space for jump, Q for blink, and click for walking or interaction.", 4, (122, "[WASD] move   [SHIFT] sprint   [SPACE] jump   [Q] blink   [CLICK] walk / interact")),
        q("When does the bottom controls legend disappear and return?", "It fades out after the player starts moving and returns when the game is paused.", 4, (122, "**smoothly fades out** once you start moving"), (122, "unless you pause")),
        q("How far do free hops and vaults reach during a sprint-jump?", "A sprint free hop covers 1.6 tiles instead of one, and vault reach increases from two to 3.2 tiles.", 4, (126, "**Free hop distance** | 1.0 tile | 1.6 tiles"), (126, "**Vault reach** | 2.0 tiles | 3.2 tiles")),
        q("How does sprinting change a jump's arc and stamina behavior?", "The jump travels 1.6 times farther, rises higher, finishes 20 percent faster, continues sprint drain in mid-air, and keeps producing a ghost trail.", 4, (126, "**Landing distance** | standard | 1.6× further"), (126, "**Arc duration** | standard | 20% faster/snappier"), (126, "vault cost + sprint drain continues mid-air"), (126, "ghost trail keeps spawning during the arc")),
    ],
    "startupsimulator_05_lighting-power": [
        q("Where is the office light switch located?", "It is a one-tile switch on the right wall at x=15,y=4 with a walkable interaction target at x=14,y=4.5.", 4, (19, "`x:15, y:4`"), (19, "interaction target at `x:14, y:4.5`")),
        q("How is the overhead-light state initialized and preserved?", "The lights start on, and the lightOn value is restored from saved state across sessions.", 4, (19, "Added `lightOn: true` to `newState()` so the lights start on"), (19, "so the light state persists across sessions")),
        q("What visual effect appears when the overhead lights are off?", "An 82-percent darkness veil covers the room while the workstation emits a soft blue monitor glow.", 4, (19, "an 82% dark veil over the whole room with a soft blue **monitor glow**")),
        q("Where was the independently controlled floor lamp placed?", "At x=9,y=9 in the lounge, with its approach target at x=9,y=8.5.", 4, (34, "lamp` object at tile `x:9, y:9`"), (34, "`target: {x:9, y:8.5}`")),
        q("Which three lighting combinations became possible after adding the lamp?", "Both lights on, overhead lights off with the lamp on, or both lighting systems off.", 4, (34, "**Three distinct lighting states are now possible:** both on (bright office), lights off + lamp on (moody warm corner), or everything off")),
        q("How does sitting on the sofa affect position, movement, and energy?", "Alex snaps to the sofa's center, cannot move, recovers two energy every two seconds, and automatically stands at full energy.", 4, (68, "snaps Alex to seat position `(14.0, 7.5)`"), (68, "movement is blocked entirely; energy recovers +2 per 2 seconds"), (68, "auto-stands when energy hits 100")),
        q("Which controls make Alex stand up from the sofa?", "Any movement key or E stands Alex up immediately; interacting with the sofa again also toggles the seated state.", 4, (68, "Any movement key or `E` stands back up instantly"), (68, "sofa dialog also toggles if you interact again while sitting")),
        q("How does the player control sofa recline?", "While seated, Up or W reclines farther, Down or S returns upright, and horizontal movement keys or E stand up.", 4, (83, "**↑ / W** | Recline further back"), (83, "**↓ / S** | Sit back upright"), (83, "**← / →, A, D** | Stand up immediately"), (83, "**E** | Stand up immediately")),
        q("How quickly does the sofa move between upright and fully reclined?", "The recline value changes at 0.9 per second, taking about 1.1 seconds end to end.", 4, (83, "moves `sofaRecline` at `0.9/sec` — ~1.1 seconds to travel fully")),
        q("How do the character's eyes and sleep animation change at full recline?", "The eyes become nearly closed with hidden pupils above 85 percent recline, while the zzz animation becomes fully opaque, 60 percent larger, and pulses more strongly.", 4, (83, "nearly shut (0.4 tall), pupils hidden at >85%"), (83, "full opacity + 60% bigger, pulse amplitude doubles")),
        q("How is in-game time converted into the day-night color overlay?", "Minutes from 540 through 1079 are normalized to zero through one and interpolated across five color keyframes.", 4, (95, "**Normalising** `minutes` (540–1079) to `t ∈ [0, 1]`"), (95, "**Interpolating** between five colour key-frames")),
        q("What visual tint represents the end of the in-game day?", "At 6 PM the room receives a 40-percent deep-blue tint.", 4, (95, "6 PM (`t=1.00`) | deep blue `rgba(15,22,70)` @ 40%")),
        q("When and where does the moonrise shimmer appear?", "After normalized time exceeds 0.7, a cool blue-white glow fades into the upper-right wall corner.", 4, (95, "once dusk begins (t > 0.7), a cool blue-white radial glow"), (95, "upper-right wall corner")),
        q("How many window-light sources illuminate the darkened office?", "Three shafts come from the back wall, plus one daytime-only fan beam from the left wall.", 4, (105, "**Three back-wall windows**"), (105, "**One left-wall window** (daytime only)")),
        q("How do sunlight and moonlight shafts differ?", "Sunlight is warmer, more strongly slanted, and includes the left-wall shaft; moonlight is cool silver-blue, closer to overhead, and omits that shaft.", 4, (105, "Warm gold `rgb(255, 215→185, 100→45)`"), (105, "Cool silver-blue `rgb(180, 200, 255)`"), (105, "Left wall shaft | ✅ Yes | ❌ No")),
        q("How was electricity added to saved game state?", "New games start with 100 electricity, the save version increased from two to three, and restored values are clamped between zero and 100.", 4, (126, "`newState()` now includes `elec: 100`"), (126, "state version bumped 2 → 3"), (126, "proper clamping (0–100)")),
        q("What are the passive electricity drain rates?", "Idle devices consume 0.04 electricity per second, overhead lights add 0.10, and the floor lamp adds another 0.04 while enabled.", 4, (126, "Base idle draw: **0.04 ⚡/s**"), (126, "Ceiling lights **+0.10 ⚡/s**"), (126, "Floor lamp **+0.04 ⚡/s**")),
        q("What happens when electricity becomes low or reaches zero?", "At 20 percent or below the game warns the player; at zero it forces both lights off and announces a blackout.", 4, (126, "**Toast at ≤20%**"), (126, "**Blackout at 0**: forces `lightOn` and `lampOn` to `false`")),
        q("How much electricity do coffee and desk work consume?", "The coffee machine costs five electricity, and working at the desk costs eight.", 4, (126, "**Coffee machine** costs **−5 ⚡**"), (126, "**Work at desk** costs **−8 ⚡**")),
        q("Where were the generator and cycling machine placed?", "The generator occupies x=12,y=8 as a one-tile object, and the two-by-two bike begins at x=12,y=9.", 4, (143, "generator   x:12, y:8  (1×1)"), (143, "bike        x:12, y:9  (2×2)")),
        q("Did the first generator and bike implementation include charging mechanics?", "No. They initially had only interaction stubs: the generator directed the player to the bike, while the bike said its mechanics were coming later.", 5, (143, "### `game.js` — 2 new interaction stubs"), (143, "Get on the bike to charge it up."), (143, "You eye the bike. Soon…")),
        q("How does the cycling interaction build and lose pedal power?", "Each Space press adds 22 power, while the bar continuously decays at 14 units per second; Escape dismounts.", 4, (164, "each press gives `+22` power"), (164, "bar decays at **14 units/sec**"), (164, "**Press `ESC`** to dismount")),
        q("How did the cycling charge thresholds change?", "The original system began charging above 50 percent, doubled above 75, and tripled at 100; the revision shifted normal, double, and triple charging to 25–50, 50–75, and 75–100 percent and added overload above 100.", 2, (164, "| >50% | ⚡ CHARGING | +2 elec/s"), (164, "| >75% | ⚡ DOUBLE CHARGE | +4 elec/s"), (164, "| 100% | ⚡ TRIPLE CHARGE | +6 elec/s"), (182, "| 25–50% | ⚡ CHARGING | +2 elec/s"), (182, "| 50–75% | ⚡⚡ DOUBLE CHARGE | +4 elec/s"), (182, "| 75–100% | ⚡⚡⚡ TRIPLE CHARGE | +6 elec/s"), (182, "| 100%+ | 💥 OVERLOADED — Ns")),
        q("What triggers a bike breakdown and how long does it last?", "A Space press that pushes internal pedal power above 100 triggers a five-second breakdown.", 4, (182, "Any `SPACE` press that carries power **over 100** triggers a **5-second breakdown**")),
        q("What can the player do while the bike is broken?", "Space does nothing and the bike produces no charge; the bar flashes red, drains at 30 per second, and shakes until recovery resets power to zero.", 4, (182, "While broken: SPACE does nothing"), (182, "power drains fast (30/s)"), (182, "overlay **shakes**"), (182, "After 5 seconds: power resets to 0")),
    ],
    "startupsimulator_06_miscellaneous": [
        q("Where was the treadmill placed?", "It was placed against the top wall at x=8,y=0 with a two-by-one footprint and a stand target at x=9,y=1.5.", 4, (21, "`treadmill` placed at `x:8, y:0, w:2, d:1`"), (21, "Player target stand position is `x:9, y:1.5`")),
        q("How did the treadmill work before its mini-game was added?", "Using it cost 15 stamina, incremented the persistent treadmillSessions count, and showed a session-dependent toast.", 4, (21, "helper function that returns `15`"), (21, "deducts 15 stamina, increments `state.treadmillSessions`")),
        q("How did treadmill interaction evolve after the mini-game request?", "It changed from a one-shot 15-stamina action into a mountable Space-tapping mini-game with run power, pace zones, rewards, penalties, and clean or overexerted dismounts.", 2, (21, "deducts 15 stamina, increments `state.treadmillSessions`"), (53, "Treadmill interaction `perform()` now calls `mountTreadmill()` instead of one-shot stamina deduction"), (53, "`runPower` decays at **8/s** passively")),
        q("Which treadmill power zones restore or drain stamina?", "Run power from 25 through 75 restores four stamina per second, while power above 75 drains six stamina per second.", 4, (53, "Zone 25–75: **restores +4 stamina/s**"), (53, "Zone 75+: **drains −6 stamina/s**")),
        q("What causes a forced treadmill dismount?", "Reaching zero stamina forces an overexerted dismount, and three consecutive overloads also force a dismount.", 4, (53, "Zero stamina → forced dismount as overexerted"), (53, "3 consecutive overloads force dismount")),
        q("Where and when can the player order delivery food?", "The phone is at x=7,y=9, and its dialog distinguishes before 10 AM, open hours, and a closed kitchen from 10 PM onward.", 4, (71, "**`phone` object** at grid position `x:7, y:9`"), (71, "too early (<10 AM), open hours, or kitchen closed (≥10 PM)")),
        q("Does ordering food change any player stats?", "No. It is explicitly a cosmetic interaction with no stat effects.", 5, (71, "Purely cosmetic · No stats affected · Very filling emotionally")),
        q("How varied is the delivery menu?", "It cycles among twelve food toasts, including pizza, ramen, burger, salad, burrito, sushi, pho, sandwich, pasta, tacos, croissant, and dumplings.", 4, (71, "**12 rotating food toasts** (pizza, ramen, burger, salad, burrito, sushi, pho, sandwich, pasta, tacos, croissant, dumplings)")),
        q("Was the food-order randomization actually stuck on ramen?", "No. The randomization was working; incorrect and duplicated emoji codepoints made the results appear misleading.", 5, (89, "The randomization itself was working fine the whole time."), (89, "Three wrong emoji codepoints in the original `menu` array")),
        q("How does the D key distinguish dancing from walking right?", "Tapping D while completely still toggles dancing and removes D from the held-key set, while pressing it during movement keeps its normal right-walk behavior and cancels dancing.", 4, (111, "**Tap `d` while standing still**"), (111, "toggles dance on/off, clears `d` from the keys set"), (111, "**Hold `d` while moving / press while another movement key is held** → normal right-walk")),
        q("What does the dance animation look like?", "It is a four-beat routine with bouncing and alternating raised arms and stepped feet, plus a smile, shrinking shadow, and three colored floating music notes.", 4, (111, "**4-beat animation** at 180ms/beat"), (111, "**3 floating music notes** (♪ ♫ ♩) in pink/blue/yellow")),
        q("How does the ambient ghost move around the room?", "Two slow sine-wave pairs make it drift about one tile around (1.5,1.7) in the back-left corner without perfectly repeating, while a separate sine wave makes it bob vertically.", 4, (123, "wanders ~1 tile in each direction around the centre point `(1.5, 1.7)`"), (123, "never perfectly repeats"), (123, "a slow vertical sine")),
        q("What happens to the ghost animation when reduced motion is preferred?", "All animation stops and the ghost renders at a fixed 38-percent opacity without bobbing or eye shimmer.", 4, (123, "all animation completely disabled; renders at a fixed 38% opacity, no bob, no eye shimmer")),
        q("What triggers the ghost jumpscare and how soon can it repeat?", "Approaching within 1.5 tiles triggers it when the cooldown is zero, after which an eight-second cooldown prevents immediate retriggering.", 4, (137, "if distance < 1.5 tiles AND cooldown == 0"), (137, "prevents re-triggering for 8 seconds after each scare")),
        q("How does the ghost visually change during a jumpscare?", "It becomes fully opaque, stops bobbing, and its eyes turn solid red while a full-screen white-to-red flash plays.", 4, (137, "Ghost draws at **full opacity 1.0**"), (137, "**Bob freezes** at zero"), (137, "**Eyes flip to solid red**"), (137, "solid white  (instant shock)")),
        q("When do two workers swap desks?", "With exactly two workers, a random 25-to-75-second timer counts down; when it expires they swap desk indices only if neither is on strike.", 4, (145, "between **25–75 seconds**"), (145, "when exactly 2 workers exist"), (145, "if neither worker is on strike")),
        q("Why do desk interactions still find the correct worker after a swap?", "The renderer, interaction handlers, and hover lookup all resolve workers through their current deskIndex, so exchanging those values updates every dependent behavior.", 4, (145, "`interactions.desk0` / `interactions.desk1` find workers by `deskIndex`"), (145, "The hover label lookup (`state.workers.find(w => w.deskIndex === di)`) also resolves correctly")),
        q("Which desks became vaultable parkour obstacles?", "The founder's desk and both worker desks, represented by the desk and desk-small object types.", 4, (153, "`'desk'` = your founder workstation (3×2). `'desk-small'` = both worker desks (3×2 each).")),
        q("How does vaulting calculate a landing beyond a large desk?", "It offsets from the object's center by its width or depth plus 1.2 tiles, producing 4.2 horizontal or 3.2 vertical tiles for a three-by-two desk.", 4, (153, "nearestWalkable(cx + dx*(hit.w + 1.2), cy + dy*(hit.d + 1.2))"), (153, "that's `cx + dx*4.2` horizontally or `cy + dy*3.2` vertically")),
        q("What happens when a valid double jump fires?", "It resets upward velocity to 2.4, marks the jump's one-use flag, costs five energy, and plays an ascending three-tone sound.", 4, (161, "boosts jumpState.vel back up to 2.4"), (161, "sets doubleJumpUsed = true"), (161, "costs −5 energy")),
        q("How did the double-jump eligibility rule change after stamina levels were introduced?", "The original implementation used only energy above 50; the final system also requires stamina level 2 or higher, so one completed treadmill workout unlocks it while the energy threshold remains.", 2, (161, "`state.energy > 50` = **above 50 out of 100**"), (172, "**Double jump** now requires `staminaLevel >= 2` as its first gate"), (172, "The `energy > 50` check remains as the second gate.")),
        q("How many workouts are required for each stamina level increase?", "Level 1 to 2 needs one workout, 2 to 3 needs two, 3 to 4 needs three, and 4 to 5 needs four.", 4, (172, "Lv 1 → 2 :  1 workout"), (172, "Lv 2 → 3 :  2 workouts"), (172, "Lv 3 → 4 :  3 workouts"), (172, "Lv 4 → 5 :  4 workouts")),
        q("What is the maximum stamina level and total workout count needed to reach it?", "The cap is level 5, reached after ten total successful workouts.", 4, (172, "Lv 4 → 5 :  4 workouts  (10 total to max out)"), (172, "Lv 5      :  already MAX, no more progress")),
    ],
}


def main() -> None:
    summary = {}
    for folder, drafts in DRAFTS.items():
        directory = DATA / folder
        cleaned = json.loads((directory / "cleaned-chat.json").read_text(encoding="utf-8"))
        output = {"qa": []}
        seen = set()
        for number, draft in enumerate(drafts, 1):
            key = re.sub(r"\W+", "", draft["question"].casefold())
            if key in seen:
                raise ValueError(f"{folder} item {number}: duplicate question")
            seen.add(key)
            citations = []
            distinct_indices = set()
            for index, quote in draft["sources"]:
                source = cleaned[index - 1]["content"][0]["text"]
                if quote not in source:
                    raise ValueError(
                        f"{folder} item {number}: quote not found in D1:{index}: {quote!r}"
                    )
                citations.append(f'D1:{index}: "{quote}"')
                distinct_indices.add(index)
            if draft["category"] in {1, 2} and len(distinct_indices) < 2:
                raise ValueError(
                    f"{folder} item {number}: category {draft['category']} needs two messages"
                )
            output["qa"].append(
                {
                    "question": draft["question"],
                    "answer": draft["answer"],
                    "evidence": citations,
                    "category": draft["category"],
                }
            )
        (directory / "output.json").write_text(
            json.dumps(output, indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )
        summary[folder] = len(output["qa"])
    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
