#!/usr/bin/env python3
"""Generate RoomPacker QA drafts, checking every exact source excerpt."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
DATA = ROOT.parent.parent / "data"


def q(question, answer, category, *sources):
    return dict(question=question, answer=answer, category=category, sources=sources)


DRAFTS = {
    "roompacker_01_main-build": [
        q("What did the user want in the first RoomPacker prototype?", "Only a 64-by-64 chessboard that could run as a local web app.", 4, (1, "Literally just a 64x64 chess board and nothing else.")),
        q("How large was the initial board in pixels?", "Each square was 12 by 12 pixels, making the board 768 by 768 pixels.", 4, (8, "Each cell is **12×12 px**, making the full board **768×768 px**")),
        q("Why did the local launcher switch to Python's HTTP server?", "An npm cache permission issue prevented the original server approach, so the agent used the available Python 3 server.", 1, (5, "There's an npm cache permission issue on this machine."), (6, "Python 3 is available."), (6, "Python's built-in HTTP server")),
        q("How did the first hover highlight work?", "Pure CSS :hover turned a square bright yellow, with no JavaScript needed.", 4, (10, "**bright yellow** (`#f6f669`)"), (10, "No JS needed, pure CSS `:hover`.")),
        q("How did clicking a square differ visually from hovering over it?", "Clicked squares became green; hovering a selected square produced a lighter green, while ordinary hover was yellow.", 4, (15, "clicked squares turn **green** (`#7fc97f`)"), (15, "a slightly lighter green (`#a0e0a0`)")),
        q("How did the initial drag-painting gesture choose whether to select or deselect cells?", "The first cell fixed the action for the whole stroke: starting on an unselected cell selected cells, and starting on a selected cell deselected them.", 4, (18, "if you start on an unselected square, the whole drag selects; if you start on a selected one, the whole drag deselects")),
        q("How did the selection model change after the smallest-enclosing-rectangle request?", "It changed from allowing independent rectangles to maintaining one rectangle that expands to enclose the existing selection and a newly clicked cell.", 2, (24, "multiple independent rectangles"), (29, "always **exactly one rectangle**"), (29, "smallest bounding box containing the existing selection **and** the new cell")),
        q("What happens when the user clicks inside the active rectangular selection?", "The entire selection clears.", 4, (29, "**Click inside the selection** | Clears the entire selection")),
        q("How was a selected rectangle converted into a named table?", "Pressing T or the Place Table button stamped the rectangle in a palette color with a centered Table N label, then cleared the selection.", 4, (33, "**Press `T`** or click the **🪑 Place Table** button"), (33, "A **\"Table N\" label**"), (33, "The selection clears")),
        q("Could tables be dragged beyond the board boundary in the main-build thread?", "No. Tables were clamped to the board edges.", 5, (37, "Tables clamp to the board edges, can't be dragged off")),
        q("How did the initial table-movement system erase the old footprint?", "tableGrid tracked cell ownership; eraseTable restored the chess colors before stampTable painted the new position.", 4, (37, "`tableGrid[row][col]` tracks which table (by id) owns each cell"), (37, "`eraseTable()` restores cells to their original light/dark chess colours before `stampTable()` paints the new position")),
        q("How did the main-build thread handle a new table that overlapped an existing table?", "It blocked placement and briefly flashed the Place Table button red.", 4, (43, "placement is **blocked**"), (43, "button **flashes red** briefly")),
        q("What happened when a dragged table was released on a conflicting position in the main-build thread?", "It snapped back to its original position.", 4, (43, "the table **snaps back** to its original position")),
        q("How did the selection preview distinguish free cells from occupied cells?", "Free cells were yellow; cells occupied by another table were highlighted red.", 4, (51, "Free cells in the rectangle → **yellow** preview"), (51, "Cells already occupied by a table → **red** highlight")),
        q("Which border styles distinguished unplaced selections, resting tables, and moving tables?", "Selections had dotted outlines, resting tables had solid borders, and moving tables had dashed borders.", 4, (63, "**Dotted** black outline"), (63, "**Solid** border in its table colour"), (63, "**Dashed** border via `.table-rect.moving`")),
        q("How did E-based table editing preserve a table's identity?", "E lifted the table into an editable selection; T committed the new shape while preserving the same table, color, and label.", 4, (77, "**Press `E`** or click **✏️ Edit** | Lifts the table off the board"), (77, "same table, same colour, same label")),
        q("How could the user cancel a table edit?", "Escape restored the table's original position and shape.", 4, (77, "**Press `Escape`** | Cancels the edit — table snaps back to its original position and shape")),
        q("Does pressing D delete a table when no table is selected?", "No. D does nothing without a selected table; it deletes a selected table or cancels and deletes one being edited.", 5, (85, "**`D` with no table selected** | Does nothing"), (85, "Cleanly cancels the edit and removes the table in one step")),
    ],
    "roompacker_02_sofas-chairs": [
        q("What size and shape constraint did the user request for straight couches?", "A minimum of one by two cells, restricted to a one-by-N strip.", 4, (1, "minimum 1x2 and is restricted to 1xn")),
        q("How was couch placement mode activated and cancelled?", "C or the Couch button activated a purple one-by-two cursor ghost; C or Escape exited the mode.", 4, (18, "**1×2 purple ghost** follows your cursor"), (18, "Press **`C`** or **`Escape`** to exit couch mode")),
        q("What event-handling bug prevented furniture drops from committing?", "A capture-phase mouseup listener removed and nulled the drag ghost, then the global mouseup handler tried to remove it again and threw an error.", 4, (26, "tried `overlay.removeChild(ghost)` again on a now-`null` ghost, throwing a JS error")),
        q("How did the fix assign mouseup cleanup for clicks versus drags?", "The per-drag listener handled bare clicks; for a real drag it left state intact so the global handler owned the entire commit and cleanup.", 4, (26, "**Bare click** (no drag) | Removes ghost, clears `movingTable`, selects/deselects the piece"), (26, "**Real drag** | Does nothing — leaves `ghost` and `movingTable` alive")),
        q("How did the first couch-extension handles work?", "Selecting a couch exposed left and right purple handles that changed its length while retaining a one-by-N shape and at least two cells.", 4, (37, "two small **purple drag handles**"), (37, "always stays `1 × N` with a minimum width of `2` cells")),
        q("What happened if a couch resize conflicted with existing furniture in this thread?", "The resize was rejected and the couch snapped back.", 4, (37, "if conflict **snaps back** silently")),
        q("Which shortcut placed chairs and why was it chosen?", "H activated Chair mode because C was already used for couches.", 4, (47, "key `H` chosen since `C` is taken by Couch")),
        q("What did the initial chair sprite look like?", "A teal circular one-cell piece, rendered at 12 by 12 pixels.", 4, (47, "a `border-radius: 50%` circle, `12×12px` teal")),
        q("Did diagonal contact with a table satisfy the chair-placement rule in the sofas-and-chairs thread?", "No. The rule checked only the four orthogonal neighboring cells and required an actual table, not a couch or chair.", 5, (57, "Checks the 4 orthogonal neighbours `(±1, 0)` and `(0, ±1)`"), (57, "Couches and other chairs don't count — only actual tables.")),
        q("What happened when a chair was dropped away from a table under the original adjacency rule?", "The chair snapped back to its original position.", 4, (57, "a chair dropped somewhere not next to a table snaps back to its original position")),
        q("How did the occupancy data model change to support chair stacking?", "Each cell changed from one piece ID or null to an array of IDs, with stamping pushing IDs and erasing filtering them out.", 2, (50, "`tableGrid` stores the occupying piece's id at each cell"), (71, "Now it holds an **array of ids**"), (71, "`push(t.id)` (no duplicates)")),
        q("What distinguished chair conflicts from couch conflicts in this thread?", "Chairs could share cells with other chairs but were blocked by non-chair pieces; couches were blocked by every occupied cell.", 4, (79, "**Couch** | `hasConflictForCouch` | Blocks on any occupied cell"), (79, "**Chair** | `hasConflictForChair` | Only blocks on non-chair pieces")),
        q("How did rotating a selected straight couch affect its dimensions and pivot?", "It swapped height and width around the top-left corner and updated the resize handles for horizontal or vertical orientation.", 4, (93, "Swaps height ↔ width around the top-left corner"), (93, "left/right for `\"h\"`, top/bottom for `\"v\"`")),
        q("How was the L-sofa represented in the finished sofas-and-chairs thread?", "It stored an inner corner, horizontal and vertical arm lengths, and one of four direction variants; each arm had minimum length two and default length three.", 4, (138, "**`cornerR, cornerC`**"), (138, "horizontal arm length (minimum 2, default 3)"), (138, "vertical arm length (minimum 2, default 3)"), (138, "`\"se\" | \"sw\" | \"ne\" | \"nw\"`")),
        q("Did the L-sofa collision check treat its empty bounding-box area as occupied?", "No. It checked only the cells actually occupied by the L shape.", 5, (138, "conflict detection properly checks only the actual occupied cells (not the bounding box)")),
        q("What did the two L-sofa resize handles control?", "One independently extended or shrank the horizontal arm and the other the vertical arm.", 4, (138, "one at the H-arm tip (ew-resize), one at the V-arm tip (ns-resize)"), (138, "extend/shrink each arm independently")),
        q("What board-selection bug was fixed while adding the L-sofa?", "A missing if(cell) guard in mouseup could throw when the user released outside the board.", 4, (138, "missing `if (cell)` guard in the board selection `mouseup` handler"), (138, "would throw if the user released outside the board")),
        q("How did stacked chairs display their count?", "Only the top chair showed ×N when more than one chair shared the cell; a single chair had no badge, and move or delete operations refreshed the count.", 4, (153, "**Topmost chair** (last in array): if count > 1, sets badge text to `×N`"), (153, "if count === 1, clears badge"), (153, "Drag top chair away | Old cell drops to **×2**")),
    ],
    "roompacker_03_shapes-overlaps": [
        q("What connected-shape rule did the user request for custom furniture?", "Every selected cell had to be reachable through adjacent selected cells, with a maximum of sixteen grid squares.", 4, (1, "each cell can go to another if we walk only through adjacent cells"), (1, "capped at 16 grid squares")),
        q("What happened when removing a painted rug cell would disconnect its shape?", "The removal was rejected with red flash feedback.", 4, (25, "Rules enforced with red flash feedback"), (25, "removing a cell that would split the shape is rejected")),
        q("How did the rug shortcut change during the shapes thread?", "It initially used G, then the user requested and received P.", 2, (25, "toolbar button, or press **G**"), (27, "Rug button shortcut is now **[P]**")),
        q("How was a painted custom rug committed or cancelled?", "Enter committed it as a canvas polyomino and exited the mode; Escape discarded the painted cells.", 4, (25, "Press **Enter**"), (25, "Mode auto-exits after placing"), (25, "Press **Escape** to cancel and clear all painted cells")),
        q("What clockwise coordinate transform rotated a rug by ninety degrees?", "A cell's row and column offsets became column offset and height minus one minus row offset, anchored at the bounding-box top-left.", 4, (31, "new relative position is `(c, H-1-r)` where `H = rMax-rMin+1`"), (31, "re-anchor to `(rMin, cMin)`")),
        q("Did chairs need a rotation implementation in the shapes thread?", "No. Their one-cell circular shape was symmetric, so rotation was ignored.", 5, (35, "**Chair** | 1×1 circle — no rotation needed, silently ignored")),
        q("What table size limits did the user request?", "Minimum two by three cells and maximum sixteen by twenty-four cells.", 4, (38, "make tables minimum 2x3 max 16x24")),
        q("How did the live table selection respond to those size limits?", "It immediately expanded small selections to the minimum and stopped growing past the maximum.", 4, (44, "snaps up to the minimum (2 rows × 3 cols)"), (44, "stops expanding beyond 16 rows × 24 cols")),
        q("What was the initial donut furniture shape?", "A hollow rectangle with a one-cell-wide ring, minimum outer size three by three and maximum sixteen by twenty-four.", 4, (63, "solid 1-cell-wide ring"), (63, "Minimum size is **3×3**"), (63, "Maximum is **16×24**")),
        q("How did the donut-creation workflow change after the user's clarification?", "The dedicated O placement mode was removed; the user instead selected an interior rectangle in an existing table and pressed U to punch a hole.", 2, (63, "Click **🍩 Donut [O]** or press **O**"), (89, "**punching a hole through an existing table**"), (89, "Press **`U`** → the table converts to a donut")),
        q("What margin was required when punching a hole in a table?", "At least one cell of border had to remain on all four sides of the interior selection.", 4, (89, "leaving at least **1 cell of border** on all four sides")),
        q("Was the punched donut hole required to be centered?", "No. Its size and position followed the selection anywhere inside the table with the required border.", 5, (89, "Hole is **exactly the selection** — any size, any position inside the table")),
        q("How did the stored donut hole respond to movement and rotation?", "It moved with the donut and rotated ninety degrees clockwise with the outer rectangle.", 4, (89, "hole moves with the piece"), (89, "rotates outer rect and hole 90° CW together")),
        q("What became of collision blocking after free furniture overlap was implemented?", "Collision checks became visual warnings; placement, dropping, rotation, and resizing could proceed despite overlaps.", 4, (105, "Every conflict check that previously blocked an action now only drives the **visual warning**"), (105, "the action always goes through")),
        q("How did the chair-placement rule change by the end of the shapes thread?", "It changed from requiring adjacency to a table to permitting chairs anywhere, including on other furniture.", 2, (105, "Always places if adjacent to table"), (112, "Chairs can now be placed anywhere on the board")),
        q("Why was cell-background painting removed from furniture stamping?", "Each new stamp overwrote the shared grid background. Furniture already had independent overlay elements, so stamping was reduced to occupancy bookkeeping.", 4, (120, "each new stamp overwrote the previous one"), (120, "Every stamp function now **only** updates the `tableGrid[r][c]` bookkeeping array")),
        q("Does fracturing always divide an old table into exactly two pieces?", "No. The guillotine-cut algorithm can produce up to four rectangular shards and skips zero-area shards.", 5, (129, "Spawns up to 4 replacement shards"), (129, "Any shard with zero area is silently skipped")),
        q("When did table fracturing run and what color did the fragments keep?", "It ran for new placement, edit-and-replace, and table drag-drop; the resulting shards retained the victim table's color.", 4, (129, "new table place, edit-re-place, drag-drop"), (129, "**Shards keep the victim's color**")),
    ],
    "roompacker_04_chaos": [
        q("What did the first Chaos toggle do and how often?", "It shuffled and teleported all furniture every 1.2 seconds while enabled.", 4, (12, "all furniture pieces are randomly teleported"), (12, "every **1.2 seconds**")),
        q("What happened when the original teleport algorithm found no free position?", "After up to 300 random attempts, it left the piece in place.", 4, (12, "Up to 300 random positions are tried per piece; if no free spot exists, the piece stays in place")),
        q("How was an out-of-bounds L-sofa teleport prevented?", "The random corner was clamped before testing and stamping the L shape.", 4, (20, "Pass the random point through `clampLsofaCorner(r, c, lenA, lenB, variant)` first")),
        q("Why did a teleported chair leave an incorrect stack count behind?", "Only the new cell's badge was refreshed; the fix remembered the old position and refreshed both cells.", 4, (20, "`refreshChairBadge` was only called for the **new** cell"), (20, "Save `oldR`/`oldC` before erasing")),
        q("How did teleport validity change after the user said adjustment was their job?", "The original valid-position search became unconditional random relocation, allowing overlaps and chairs away from tables while retaining board bounds.", 2, (12, "valid, non-overlapping positions"), (27, "Pieces now **always teleport**"), (27, "The only thing still enforced is **board bounds**")),
        q("Could Chaos teleport a piece partly off the board after validity checks were removed?", "No. Board bounds were still enforced to prevent invalid grid indexing.", 5, (27, "pieces can't be teleported partially off the edge")),
        q("What time limit was introduced for unresolved furniture conflicts?", "Eight seconds per piece, checked every 100 milliseconds.", 4, (40, "Time limit per conflict | **8 seconds**"), (40, "Timer checks | Every 100 ms")),
        q("How did a conflict timer react to a new teleport?", "Each new landing reset the timer to a fresh eight seconds.", 4, (40, "each new landing gives a fresh 8 s")),
        q("What happened when a furniture conflict deadline expired?", "Teleporting and ticking stopped, the guilty piece glowed red, and a Game Over overlay named it and offered a page-reload retry.", 4, (40, "All teleporting and ticking stops instantly"), (40, "overlay appears, naming the piece that expired"), (40, "A **Try Again** button reloads the page")),
        q("How frequently did furniture break and how long did repair allow?", "While Chaos was active, a random piece broke every three seconds and gave the player six seconds to repair it.", 4, (52, "every **3 seconds** one random piece"), (52, "shrinking over **6 seconds**")),
        q("How did the player repair broken furniture?", "Clicking repaired it instantly and consumed the click so it did not also select the piece.", 4, (52, "**Click the piece** to repair it instantly"), (52, "it won't also select the piece")),
        q("Did repairing breakage replace the existing conflict-timeout mechanic?", "No. Breakage and conflict game-over timers remained independent.", 5, (52, "The existing conflict-timeout game-over still works independently as before.")),
        q("What probability and cadence governed random rotation?", "Each piece had a forty-percent chance to rotate ninety degrees clockwise every 1.8 seconds while Chaos was active.", 4, (61, "every **1.8 seconds** each piece independently has a **40% chance** of being rotated 90° clockwise")),
        q("Could automatic teleporting or rotation interrupt a furniture drag?", "No. Both mechanics skipped the piece currently being dragged.", 1, (12, "A piece currently being dragged by the user is **skipped**"), (61, "A piece being dragged is never rotated.")),
        q("When was the one-percent fading easter-egg roll performed?", "Once when Chaos mode was switched on; a failed roll left the fading mechanism dormant.", 4, (72, "a 1% roll that only happens when Chaos mode is switched **on**"), (72, "`fadeInterval` stays `null`")),
        q("Did the fading animation make furniture completely invisible or alter gameplay?", "No. Opacity ranged from 0.12 to 1.0 and fading did not change gameplay, collision checks, or timers.", 5, (69, "`0.12 → 1.0`"), (69, "Fading is purely visual — it doesn't affect gameplay logic, conflict detection, or timers")),
        q("How was rainbow furniture triggered and animated?", "A placement or donut punch had a one-percent chance to create rainbow furniture; its hue advanced about sixty degrees per second in a shared animation loop.", 4, (91, "there's a **1% chance** it becomes rainbow"), (91, "Every frame the hue advances **~60°/sec**")),
        q("How did the rug squiggle mechanic mutate shapes while preserving their area?", "Every 700 milliseconds it ran three swaps, removing a safely removable boundary cell and adding an adjacent empty cell; connectivity, area, and board bounds were preserved.", 4, (103, "Every **700ms**"), (103, "**3 cell-swap steps** per rug"), (103, "exactly the **same cell count**"), (103, "connectivity checked before any removal")),
    ],
    "roompacker_05_3d-floating": [
        q("Which rendering library replaced RoomPacker's 2D CSS board?", "Three.js rendered the replacement WebGL 3D scene.", 4, (20, "**Three.js WebGL 3D scene**")),
        q("Why was Three.js loaded through a CDN?", "The project was a static HTML file with no bundler, served through Python's HTTP server.", 4, (5, "Use Three.js (via CDN) since no bundler is in use"), (5, "static HTML file served with `python3 -m http.server`")),
        q("What camera and mouse controls accompanied the first 3D conversion?", "An orthographic isometric camera allowed right-drag orbiting and scroll-wheel zoom.", 4, (20, "Orthographic isometric view — right-drag or scroll to orbit/zoom")),
        q("What shape represented chairs in the first 3D version?", "Cylinders with a round cross-section.", 4, (20, "**Chairs** | Cylinders (round cross-section)")),
        q("What did the arrow keys do after keyboard furniture control was added?", "They nudged a selected piece one cell north, south, west, or east while preventing browser scrolling.", 4, (25, "one grid cell at a time"), (25, "arrow keys don't also scroll the page")),
        q("Could arrow-key nudges push pieces off the grid?", "No. Piece positions were clamped to the grid boundary.", 5, (25, "Pieces are **clamped to the grid boundary**")),
        q("Which keys controlled clockwise and counter-clockwise rotation in 3D?", "Q rotated counter-clockwise; E rotated clockwise, with R retained as a clockwise alias.", 4, (32, "`Q` | Rotate **counter-clockwise**"), (32, "`E` | Rotate **clockwise**"), (32, "`R` | Also rotates CW")),
        q("How did counter-clockwise rotation transform a rug's cell offsets?", "It mapped row and column offsets to width minus one minus column offset, and row offset.", 4, (32, "90° CCW: `(dr,dc)→(W-1-dc, dr)`")),
        q("How did the placement space expand after the 64-by-64-by-64 request?", "The first 3D floor was 32 by 32; it was replaced by a cube with six independent 64-by-64 placement faces.", 2, (20, "32×32 alternating light/dark tile grid"), (39, "6 placeable faces"), (39, "independent **64×64 grid**")),
        q("How were cube-face shortcuts mapped?", "Keys 1 through 6 selected Top, Bottom, Front, Back, Left, and Right respectively.", 4, (39, "**Top** / `1`"), (39, "**Bottom** / `2`"), (39, "**Front** / `3`"), (39, "**Back** / `4`"), (39, "**Left** / `5`"), (39, "**Right** / `6`")),
        q("How did the display distinguish the active cube face?", "The active face used full-brightness tiles, other faces were dimmed, and a top-right indicator identified the current face.", 4, (39, "active face is highlighted** (full brightness tiles)"), (39, "all others are dimmed"), (39, "**face indicator** in the top-right corner")),
        q("Did Chaos teleportation move furniture between cube faces?", "The described behavior kept pieces within their own face.", 5, (39, "Chaos mode teleports all pieces randomly (within their own face)")),
        q("What were the requested final heights for tables, sofas, L-sofas, and chairs?", "Tables were one grid unit tall; straight sofas, L-sofas, and chairs were two units tall.", 1, (42, "`H_COUCH` and `H_LSOFA` are both now `2.0`"), (44, "`H_CHAIR` is now `2.0`"), (46, "`H_TABLE` is now `1.0`")),
        q("Which furniture did the agent redesign after the vague request that abnormal furniture be unique?", "The agent redesigned the L-sofa, adding seats and backrests; the user's message did not explicitly identify that type.", 4, (47, "the abnormal furniture is going to be unique"), (49, "The L-sofa currently renders as a cluster of plain `BoxGeometry` cells"), (54, "Each cell has a **wide seat**")),
        q("How did the redesigned two-unit L-sofa divide its height?", "The seat used 1.2 units and the backrest 0.8, totaling two.", 4, (57, "seat occupies 1.2 units (60%) and the backrest sits on top at 0.8 units (40%)")),
        q("What per-piece field tracked floating distance?", "floatDepth tracked integer steps from the face surface and initialized to zero.", 4, (61, "Add `floatDepth=0` to every piece (integer grid steps along the normal)")),
        q("How did W and S control floating furniture?", "W moved a selected piece one grid step outward along the face normal; S brought it back inward.", 4, (62, "press **`W`** to float it one grid step outward along the face normal"), (62, "**`S`** to bring it back in")),
        q("What range was reported for floatDepth and how did selection feedback follow it?", "The field was clamped from zero to sixty-three, and the selection halo followed the piece's floating height.", 4, (62, "`floatDepth` is clamped to `[0, 63]`"), (62, "selection halo follows the piece at whatever height it's floating at")),
    ],
    "roompacker_06_colors-merging": [
        q("How did the initially added opacity slider become available?", "Selecting a furniture piece enabled the toolbar slider and showed that piece's opacity as a percentage.", 4, (20, "**Disabled** when no piece is selected; **enabled** automatically when you click a piece"), (20, "Displays the current opacity as a percentage")),
        q("What transparency range and step size did the original slider offer?", "Zero percent to one hundred percent, in five-percent steps.", 4, (20, "Range: `0%` (invisible) → `100%` (fully opaque), in 5% steps")),
        q("How were furniture edges kept visible when the bodies became transparent?", "Fully opaque LineSegments were attached to the geometry; the mesh-opacity helper skipped those line objects.", 4, (31, "**always fully opaque** (`transparent: false, opacity: 1`)"), (31, "`LineSegments` are not `Mesh` objects, `setMeshOpacity` already skips them")),
        q("What did liftColor do for furniture edge outlines?", "It blended the piece's color toward white to create lighter matching edge lines.", 4, (31, "blends a colour toward white by factor `t`")),
        q("How was the opacity control improved for exact input?", "A number input was added beside a zero-to-one-hundred slider; the two stayed synchronized and numeric values were clamped on Enter or blur.", 4, (40, "**Number input**"), (40, "Both inputs **stay in sync**"), (40, "number input **clamps on blur/Enter**")),
        q("How did transparency support change by the end of the visual-refinements thread?", "It was first implemented with adjustable per-piece opacity, then removed at the user's request, including the controls and opacity fields.", 2, (20, "furniture pieces in Room Packer 3D can now be made transparent"), (53, "Remove the transparency feature"), (71, "`opacity:` field removed from all piece data objects")),
        q("Did removing furniture transparency also make placement previews opaque?", "No. Ghost and selection previews retained their own transparent materials.", 5, (71, "ghost previews still render semi-transparent as intended"), (71, "selection rect still renders semi-transparent as intended")),
        q("What rendering technique created the first three-layer selection glow?", "Concentric BackSide box shells with unlit MeshBasicMaterial produced an outer corona, and depthWrite false prevented occlusion.", 4, (46, "**3-layer concentric glow corona**"), (46, "`MeshBasicMaterial`"), (46, "`depthWrite: false` prevents the shells from occluding anything behind them")),
        q("How many particles did the temporary sparkle effect use and how were they recycled?", "It used sixty particles whose lifetimes ranged from 0.6 to 1.4 seconds; expired particles respawned at new surface points.", 4, (52, "pool of **60 sparkles**"), (52, "random lifetime (0.6–1.4 s)"), (52, "**respawns** at a fresh random surface point")),
        q("How did the selection effect change after the user requested a reddish glow?", "The sparkle particles and texture were removed and replaced by three red-toned glow shells, retaining the breathing pulse.", 2, (52, "`THREE.Points` object"), (76, "All sparkle code is gone"), (76, "simple 3-shell reddish corona"), (76, "breathing pulse animation is unchanged")),
        q("Which three colors defined the final reddish selection glow?", "The inner shell was orange-red #ff6644, the middle pure red #ff2200, and the outer deep red #880000.", 4, (76, "`#ff6644` orange-red"), (76, "`#ff2200` pure red"), (76, "`#880000` deep red")),
        q("Which rendering settings were matched for the greenish room background?", "The page background, WebGL clear color, and scene fog all became dark forest green #0a1a0f so they blended seamlessly.", 4, (79, "CSS `body` background"), (79, "`renderer.setClearColor`"), (79, "`scene.fog`"), (79, "same `#0a1a0f`")),
        q("How did the furniture color picker behave with and without a selected piece?", "With a piece selected it recolored that piece immediately; without one it stored the color for the next placement.", 4, (92, "**Piece selected** | Immediately recolours the selected piece live"), (92, "**Nothing selected** | Stores the colour as `nextColor`")),
        q("What conditions enabled merging two furniture pieces?", "They had to be distinct pieces with exactly the same color on the same cube face.", 4, (97, "same face, same color (close enough, ±0), not same piece"), (115, "**exact same color**")),
        q("What preview appeared while hovering a valid merge target?", "A semi-transparent ghost displayed the combined footprint of both pieces in their shared color.", 4, (115, "a semi-transparent ghost preview shows the **combined footprint** of both pieces together in their shared color")),
        q("What happened to the originals after a furniture merge?", "Both were deleted and replaced by one selected merged piece containing all their cells and retaining the shared color.", 4, (115, "both originals are deleted and replaced by a single `merged` piece containing all their cells"), (115, "new piece is automatically selected, still showing the same color")),
        q("Did merged furniture have to consist of two pieces of the same type?", "No. Any supported furniture type could merge with another compatible same-color piece, including a previously merged piece.", 5, (115, "Any furniture type (table, sofa, chair, L-sofa, rug, previously-merged) can be merged with any other")),
        q("Which height did a merged piece inherit?", "It inherited the taller of the two source heights.", 4, (115, "The merged piece inherits the **taller** of the two heights")),
        q("How could merging be chained or cancelled?", "A merged piece could merge again without a chaining limit; clicking elsewhere or pressing Escape cancelled the current merge mode.", 4, (115, "chaining is unlimited"), (115, "**Click anywhere else** or press **`Escape`** — cancels merge mode with no changes")),
    ],
}


def main():
    from quality_annotations import curated
    selected, audits = curated(DRAFTS)
    counts = {}
    for folder, drafts in selected.items():
        directory = DATA / folder
        cleaned = json.loads((directory / "cleaned-chat.json").read_text())
        rows = []
        for number, draft in enumerate(drafts, 1):
            citations = []
            for index, quote in draft["sources"]:
                source = cleaned[index - 1]["content"][0]["text"]
                if quote not in source:
                    raise ValueError(f"{folder} item {number}: quote missing at D1:{index}: {quote!r}")
                citations.append(f'D1:{index}: "{quote}"')
            rows.append({key: draft[key] for key in ("question", "answer", "category")})
            rows[-1]["evidence"] = citations
        (directory / "output.json").write_text(json.dumps({"qa": rows}, indent=2, ensure_ascii=False) + "\n")
        counts[folder] = len(rows)
    (ROOT / "evidence/local-semantic-review.json").write_text(json.dumps(audits, indent=2, ensure_ascii=False) + "\n")
    print(json.dumps(counts, indent=2))


if __name__ == "__main__":
    main()
